
#ifdef SCREENSHOT_FEATURES


#ifdef DOF_INTENSITY
#undef DOF_INTENSITY
uniform float DOF_INTENSITY;
#endif


#ifdef WEATHER_TEMPERATURE_BIAS
#undef WEATHER_TEMPERATURE_BIAS
uniform float WEATHER_TEMPERATURE_BIAS;
#endif


#ifdef WEATHER_HUMIDITY_BIAS
#undef WEATHER_HUMIDITY_BIAS
uniform float WEATHER_HUMIDITY_BIAS;
#endif


#ifdef WEATHER_WIND_BIAS
#undef WEATHER_WIND_BIAS
uniform float WEATHER_WIND_BIAS;
#endif


#ifdef WEATHER_TEMPERATURE_VARIATION_SPEED
#undef WEATHER_TEMPERATURE_VARIATION_SPEED
uniform float WEATHER_TEMPERATURE_VARIATION_SPEED;
#endif


#ifdef WEATHER_HUMIDITY_VARIATION_SPEED
#undef WEATHER_HUMIDITY_VARIATION_SPEED
uniform float WEATHER_HUMIDITY_VARIATION_SPEED;
#endif


#ifdef WEATHER_WIND_VARIATION_SPEED
#undef WEATHER_WIND_VARIATION_SPEED
uniform float WEATHER_WIND_VARIATION_SPEED;
#endif


#ifdef SWAY_STRENGTH
#undef SWAY_STRENGTH
uniform float SWAY_STRENGTH;
#endif


#ifdef SWAY_SPACE_VARIATION_STRENGTH
#undef SWAY_SPACE_VARIATION_STRENGTH
uniform float SWAY_SPACE_VARIATION_STRENGTH;
#endif


#ifdef SWAY_SPACE_VARIATION_DIRECTION
#undef SWAY_SPACE_VARIATION_DIRECTION
uniform float SWAY_SPACE_VARIATION_DIRECTION;
#endif


#ifdef SWAY_TIME_VARIATION
#undef SWAY_TIME_VARIATION
uniform float SWAY_TIME_VARIATION;
#endif


#ifdef SWAY_ANGLE
#undef SWAY_ANGLE
uniform float SWAY_ANGLE;
#endif


#endif

